# Generated by Django 5.1.3 on 2025-02-12 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articolo_dataarticolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='dataArticolo',
            field=models.DateField(db_default=datetime.datetime(2025, 2, 12, 10, 25, 0, 535010)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(db_default=datetime.datetime(2025, 2, 12, 10, 25, 0, 535010)),
        ),
    ]
