# Generated by Django 5.1.3 on 2025-03-26 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_articolo_dataarticolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='dataArticolo',
            field=models.DateField(db_default=datetime.datetime(2025, 3, 26, 11, 33, 42, 985864)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(db_default=datetime.datetime(2025, 3, 26, 11, 33, 42, 985864)),
        ),
    ]
