# Generated by Django 5.1.3 on 2025-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_articolo_dataarticolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='dataArticolo',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(auto_now_add=True),
        ),
    ]
