# Generated by Django 5.1.3 on 2025-03-26 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corso',
            options={'verbose_name': 'Corso', 'verbose_name_plural': 'Corsi'},
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateField(db_default=datetime.datetime(2025, 3, 26, 11, 33, 42, 985864)),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateField(db_default=datetime.datetime(2025, 3, 26, 11, 33, 42, 985864)),
        ),
    ]
