# Generated by Django 5.1.3 on 2025-05-28 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0002_alter_corso_options_alter_corso_data_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateField(db_default=datetime.datetime(2025, 5, 28, 10, 57, 0, 176657)),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateField(db_default=datetime.datetime(2025, 5, 28, 10, 57, 0, 176657)),
        ),
    ]
